baseurl = "https://mfbmina.dev"
DefaultContentLanguage = "br"
title = "Matheus Mina"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[languages]
  [languages.br]
    contentDir = 'content/br'
  [languages.en]
    contentDir = 'content/en'

[params]
  logo = "img/me.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "02/01/2006"
  comments = true
  readingTime = true
  wordCount = false
  useHLJS = true
  socialShare = true
  showRelatedPosts = true
  hideAuthor = true
  [params.Author]
    name = "Matheus Mina"
    website = "mfbmina.dev"
    email = "mfbmina@gmail.com"
    github = "mfbmina"
    twitter = "mfbmina"
    linkedin = "mfbmina"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
