baseurl = "https://mfbmina.dev"
DefaultContentLanguage = "br"
title = "mfbmina.dev"
subtitle = "Matheus Mina"
theme = ""
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[languages]
  [languages.br]
    contentDir = 'content/br'
  [languages.en]
    contentDir = 'content/en'

[params]
  homeTitle = "mfbmina.dev"
  subtitle = "by Matheus Mina"
  logo = "img/me.png"
  ShareImg = "img/gopher.png"
  favicon = "img/favicon.ico"
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  showRelatedPosts = true
  hideAuthor = true
  [params.author]
    name = "Matheus Mina"
    website = "https://mfbmina.dev"
    email = "mfbmina@gmail.com"
    github = "mfbmina"
    twitter = "mfbmina"
    linkedin = "mfbmina"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
