baseURL = "http://mfbmina.dev/"
theme = "LoveIt"
title = "mfbmina.dev"

# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true

[languages]
  [languages.en]
    disabled = false
    languageCode = ''
    languageDirection = ''
    languageName = 'English'
    weight = 0
  [languages.pt-br]
    disabled = false
    languageCode = 'pt-br'
    languageDirection = ''
    languageName = 'Português'
    weight = 0

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "Talks"
    pre = ""
    post = ""
    name = "Talks"
    url = "/Talks/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about"
    title = ""

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[params]
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  gitRepo = "https://github.com/mfmbina/mfbmina.dev"
  dateFormat = "02/01/2006"
  # website title for Open Graph and Twitter Cards
  title = "mfbmina.dev"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = "by Matheus Mina"
  # website images for Open Graph and Twitter Cards
  images = ["/img/gopher.png"]

# Author config
  [params.author]
    name = "Matheus Mina"
    email = "mfbmina@gmail.com"
    link = "https://mfbmina.dev"

  # Header config
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    [params.header.title]
      # URL of the LOGO
      logo = "/img/gopher.png"
      # title name
      name = "mfbmina.dev"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = true
