baseurl = "https://mfbmina.dev"
DefaultContentLanguage = "br"
title = "Matheus Mina"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
disqusShortname = 'mfbmina'

[languages]
  [languages.br]
    contentDir = 'content/br'
  [languages.en]
    contentDir = 'content/en'

[Params]
  logo = "img/me.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "02/01/2006"
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true

[Author]
  name = "Matheus Mina"
  website = "mfbmina.dev"
  email = "mfbmina@gmail.com"
  github = "mfbmina"
  twitter = "mfbmina"
  linkedin = "mfbmina"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
