baseurl = "https://mfbmina.dev"
DefaultContentLanguage = "br"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
subtitle = "Matheus Mina"
title = "mfbmina.dev"

[languages]
  [languages.br]
    contentDir = 'content/br'
  [languages.en]
    contentDir = 'content/en'

[params]
  comments = true
  favicon = "img/favicon.ico"
  hideAuthor = true
  homeTitle = "mfbmina.dev"
  logo = "img/me.png"
  readingTime = true
  rss = true
  selfHosted = false
  shareImg = "img/gopher.png"
  showRelatedPosts = true
  socialShare = true
  subtitle = "by Matheus Mina"
  useHLJS = false
  wordCount = true
  [params.author]
    name = "Matheus Mina"
    website = "https://mfbmina.dev"
    email = "mfbmina@gmail.com"
    github = "mfbmina"
    bluesky = "mfbmina.dev"
    twitter = "mfbmina"
    linkedin = "mfbmina"
    devto = "mfbmina"
    telegram = "mfbmina"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
