baseURL = 'https://mfbmina.github.io/'
defaultContentLanguage = 'pt-br'
defaultContentLanguageInSubdir = true
languageCode = 'pt-br'
title = 'Matheus Mina'
theme = 'ananke'

[languages]
  [languages.pt-br]
    contentDir = 'content/pt-br'
    disabled = false
    languageCode = 'pt-BR'
    languageDirection = 'ltr'
    languageName = 'pt-br'
    weight = 1
    read_more_copy = 'Leia mais'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'en'
    weight = 2
    read_more_copy = "Read more"


[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/mfbmina"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/mfbmina"

[[params.ananke_socials]]
name = "linkedin"
url = "https://linkedin.com/in/mfbmina"

[[params.ananke_socials]]
name = "email"
url = "mfbmina@gmail.com"
rel = "mailto"
